/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.michaelceley.versions

import picocli.CommandLine
import kotlin.system.exitProcess

class VersionFetcher : Runnable {

    override fun run() {
        println("Make this thing do the thing.")
    }
}

fun main(args: Array<String>) {
    val exitCode = CommandLine(VersionFetcher()).execute(*args)
    exitProcess(exitCode)
}
